version: '3.8'

services:
  litetts:
    build: .
    container_name: litetts-api
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - CACHE_ENABLED=true
      - LITETTS_WORKERS=4
      - LITETTS_CACHE_SIZE=2000
      - LITETTS_WATERMARKING_ENABLED=true
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./LiteTTS/models:/app/LiteTTS/models:ro
      - ./LiteTTS/voices:/app/LiteTTS/voices
      - litetts-cache:/app/LiteTTS/cache
      - litetts-logs:/app/docs/logs
    restart: unless-stopped
    networks:
      - owui-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8354/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    environment:
      - AUDIO_TTS_ENGINE=custom
      - AUDIO_TTS_API_URL=http://litetts:8354
      - AUDIO_TTS_API_KEY=not-needed
      - AUDIO_TTS_VOICE=af_heart  # Set a default voice
      - CHROMA_URL=http://chroma:8000
    volumes:
      - openwebui-data:/app/backend/data
    depends_on:
      - litetts
      - chroma
    restart: unless-stopped
    networks:
      - owui-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"  # Comment out for production (best practice)
      # Uncomment the following line to enable HTTPS
      # - "${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
    networks:
      - owui-network

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped
    networks:
      - owui-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s

volumes:
  litetts-cache:
  litetts-logs:
  openwebui-data:
  caddy-data:
  caddy-config:
  chroma-data:

networks:
  owui-network:
    driver: bridge