version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "443:8080"  # Map host 443 to container 8080
    volumes:
      - ./data:/app/backend/data  # Persist data
      - ./certs:/app/backend/certs  # TLS certificates
    environment:
      - WEBUI_SECRET_KEY=your-secret-key-change-me  # Change this!
      - OLLAMA_API_BASE_URL=  # Empty to disable Ollama
      - OPENROUTER_API_BASE_URL=https://openrouter.ai/api/v1
      - OPENROUTER_API_KEY=your-openrouter-api-key  # Replace with your key
      - GOOGLE_AI_STUDIO_API_KEY=your-google-ai-studio-api-key  # Replace with your key
      - DISABLE_SIGNUP=false  # Set to true to disable new signups
      - ENABLE_SIGNUP=false  # Alternative way to disable signups
      - WEBUI_AUTH=login  # Require login
      - WEBUI_JWT_SECRET=your-jwt-secret-change-me  # Change this!
      - WEBUI_HTTPS=true  # Enable HTTPS
      - WEBUI_CERT_FILE=/app/backend/certs/fullchain.pem
      - WEBUI_KEY_FILE=/app/backend/certs/privkey.pem
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
