version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-t0p-s3cr3t}
      - DISABLE_MODEL_FETCH=true
      - ENABLE_OPENAPI_API=true
      - ENABLE_OLLAMA_API=False
      - ENABLE_SIGNUP=false
      - ENABLE_CHANNELS=true
      - ENABLE_ADMIN_EXPORT=true
      - ENABLE_TITLE_GENERATION=true
      - ENABLE_WEB_SEARCH=true
      - WEB_SEARCH_TRUST_ENV=true
      - WEB_SEARCH_RESULT_COUNT=10
      - WEB_SEARCH_ENGINE=duckduckgo
      - AUDIO_TTS_OPENAI_API_BASE_URL=http://15.204.226.76:8354
      - AUDIO_TTS_OPENAI_API_KEY=not-needed
      - AUDIO_TTS_ENGINE=openai
      - AUDIO_TTS_MODEL=tts-1
      - AUDIO_TTS_VOICE=af_heart
      - AUDIO_TTS_API_KEY=not-needed
      - WHISPER_MODEL=turbo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - webui-network

  caddy:
    image: caddy:latest
    container_name: caddy-webui
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /home/debian/ssl:/etc/caddy/ssl:ro
    depends_on:
      open-webui:
        condition: service_healthy
    networks:
      - webui-network

volumes:
  open-webui-data:
  caddy_data:
  caddy_config:

networks:
  webui-network:
    driver: bridge